server:
  port: ${PORT:8081}
  servlet:
    context-path: /store
  error:
    whitelabel:
      enabled: true

#logging:
#  file:
#    name: store.log
#    path: module2/log/

spring:
  profiles:
    active: dev
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3308/fruit_db}
    username: ${DATASOURCE_USER:dev}
    password: ${DATASOURCE_PASS:password}
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 6
          max-interval: 5s
          multiplier: 2
      direct:
        auto-startup: false
