server:
  port: ${PORT:8080}
  servlet:
    context-path: /store
  error:
    whitelabel:
      enabled: true

logging:
  file:
    name: store.log

spring:
  profiles:
    active: dev
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3308/fruit_db
#    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3308/fruit_db}
    username: dev
    password: password
#    username: ${DATASOURCE_USER:dev}
#    password: ${DATASOURCE_PASS:password}
