POST http://localhost:8081/store/api/orders/ HTTP/1.1
Content-Type: application/json

{
  "orderLine": [
    {
      "productId": "0fe35c12-ad71-4d7a-8e5e-8df63f934b53",
      "amount": 43
    }
  ]
}

###

DELETE http://localhost:8081/store/api/orders/27f9e69a-108c-423b-b9ce-eccc145f2892 HTTP/1.1
