server:
  port: ${PORT:8080}
  servlet:
    context-path: /warehouse

spring:
  profiles:
    active: dev,shell
  shell:
    interactive:
      enabled: false
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:mysql://172.18.0.1:3308/fruit_db"
    username: "dev"
    password: "password"
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1s
          max-attempts: 6
          max-interval: 5s
          multiplier: 2
      direct:
        auto-startup: false
# Dev
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
logging:
  level:
    com.bmac.warehouse: DEBUG

# Seed
---
spring:
  config:
    activate:
      on-profile: seed
  jpa:
    hibernate:
      ddl-auto: create

# Shell
---
spring:
  config:
    activate:
      on-profile: shell
  shell:
    interactive:
      enabled: true
