version: '3.8'

services:
  fruit_db:
    image: mysql:8.0.30
    container_name: fruit_db
    restart: always
    environment:
      MYSQL_DATABASE: 'fruit_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    networks:
      - backend
#    volumes:
#      - ./mysql/data:/var/lib/mysql
    user: mysql

networks:
  backend:
    name: back-network
    driver: bridge
