version: '3.8'

services:
  mysql_fruit_db:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_DATABASE: 'fruit_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    networks:
      - backend
    volumes:
      - ./mysql/data:/var/lib/mysql:rw
    user: mysql

networks:
  backend:
    name: back-network
    driver: bridge
